behaviors:
  O_Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0002
      beta: 0.003
      epsilon: 0.15
      lambd: 0.93
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 5
    summary_freq: 1000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 10000
      swap_steps: 10000
      team_change : 40000

  X_Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0002
      beta: 0.003
      epsilon: 0.15
      lambd: 0.93
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 5
    summary_freq: 1000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 10000
      swap_steps: 10000
      team_change : 40000

engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true

checkpoint_settings:
  run_id: Self_TTT_1
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false

